// playgrounds/svelte/src/tonconnect/TonConnectButton.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { useTonConnectUI } from './useTonConnectUI';
  import { derived } from 'svelte/store';

  let { id = 'tonconnect-button' } = $props();

  const contextValue = useTonConnectUI();

  const setTonConnectUIOptions = derived(
    contextValue,
    ($contextValue) => $contextValue.setTonConnectUIOptions
  );

  onMount(() => {
    $setTonConnectUIOptions({ buttonRootId: id });
  });

  onDestroy(() => {
    $setTonConnectUIOptions({ buttonRootId: null });
  });
</script>

<div {id} style="width: 'fit-content'"></div>

// playgrounds/vue/src/tonconnect/TonConnectButton.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { useTonConnectUI } from './useTonConnectUI';

const props = withDefaults(defineProps<{
  id?: string
}>(), { id: 'tonconnect-button' });

const { setTonConnectUIOptions } = useTonConnectUI();

onMounted(() => {
  setTonConnectUIOptions({ buttonRootId: props.id });
});

onUnmounted(() => {
  setTonConnectUIOptions({ buttonRootId: null });
});
</script>

<template>
  <div :id :style="{ width: 'fit-content' }"></div>
</template>
