// playgrounds/svelte/src/components/DisplayData/DisplayData.svelte
<script module lang="ts">
  export interface IRow {
    title: string;
    value?: RGB | string | number | boolean | Snippet;
  }

  interface IProps {
    rows: IRow[];
  }
</script>

<script lang="ts">
  import './DisplayData.css';

  import { type Snippet } from 'svelte';
  import RGBRender from '@/components/RGB/RGB.svelte';
  import { isRGB, type RGB } from '@telegram-apps/sdk-svelte';

  const { rows }: IProps = $props();

  function mapValueToString(value?: boolean | string) {
    switch (value) {
      case true:
        return '✔️';
      case false:
        return '❌';
      case undefined:
        return 'empty';
      default:
        return value;
    }
  }
</script>

<div>
  {#each rows as { title, value, meta }}
    <div class="display-data__line">
      <span class="display-data__line-title">{title}</span>
      <span class="display-data__line-value">
        {#if meta}
          {@const Component = value}
          <Component {...meta} />
        {:else if typeof value === 'string' && isRGB(value) && typeof value === 'string' && isRGB(value)}
          <RGBRender color={value} />
        {:else}
          <span>{mapValueToString(value)}</span>
        {/if}
      </span>
    </div>
  {/each}
</div>

// playgrounds/solid/src/components/DisplayData/DisplayData.tsx
import { isRGB, type RGB as RGBType } from '@telegram-apps/sdk-solid';
import { type Component, For, type JSXElement, Match, Switch } from 'solid-js';

import { RGB } from '@/components/RGB/RGB.js';

import './DisplayData.css';

export interface DisplayDataRow {
  title: string;
  value?: RGBType | string | boolean | JSXElement;
}

export interface DisplayDataProps {
  rows: DisplayDataRow[];
}

export const DisplayData: Component<DisplayDataProps> = (props) => {
  return (
    <div>
      <For each={props.rows}>
        {(row) => (
          <div class="display-data__line">
            <span class="display-data__line-title">{row.title}</span>
            <span class="display-data__line-value">
              <Switch fallback={row.value}>
                <Match when={typeof row.value === 'string' && isRGB(row.value) ? row.value : false}>
                  {(color) => <RGB color={color()}/>}
                </Match>
                <Match when={row.value === false}>❌</Match>
                <Match when={row.value === true}>✔️</Match>
                <Match when={row.value === undefined}><i>empty</i></Match>
              </Switch>
            </span>
          </div>
        )}
      </For>
    </div>
  );
};
