// templates/solidjs-js-template/src/components/RGB/RGB.jsx
import { classNames } from '@tma.js/sdk-solid';
import { splitProps } from 'solid-js';

import './RGB.css';

/**
 * @typedef RGBProps
 * @extends {import('solid-js').JSX.IntrinsicElements['span']}
 * @property {import('@tma.js/sdk-solid').RGB} color
 */

/**
 * @param {RGBProps} props
 * @return {import('solid-js').JSXElement}
 */
export function RGB(props) {
  return (
    <span {...splitProps(props, ['class'])[0]} class={classNames('rgb', props.class)}>
      <i class="rgb__icon" style={{ 'background-color': props.color }}/>
        {props.color}
    </span>
  );
}

// playgrounds/react/src/components/RGB/RGB.tsx
import { classNames, type RGB as RGBType } from '@tma.js/sdk-react';
import type { FC } from 'react';

import './RGB.css';

export type RGBProps = JSX.IntrinsicElements['div'] & {
  color: RGBType;
};

export const RGB: FC<RGBProps> = ({ color, className, ...rest }) => (
  <span {...rest} className={classNames('rgb', className)}>
    <i className='rgb__icon' style={{ backgroundColor: color }}/>
    {color}
  </span>
);
