// apps/react/src/pages/InitDataPage/InitDataPage.tsx
import { type FC, type ReactNode, useMemo } from 'react';
import { useInitData, useLaunchParams, type User } from '@tma.js/sdk-react';

import { DisplayData, type DisplayDataRow } from '@/components/DisplayData/DisplayData.tsx';
import { Link } from '@/components/Link/Link.tsx';
import { Page } from '@/components/Page/Page.tsx';

import './InitDataPage.css';

function getUserRows(user: User): DisplayDataRow[] {
  return [
    { title: 'id', value: user.id.toString() },
    { title: 'last_name', value: user.lastName },
    { title: 'first_name', value: user.firstName },
    { title: 'is_bot', value: user.isBot },
    { title: 'is_premium', value: user.isPremium },
    { title: 'language_code', value: user.languageCode },
  ];
}

export const InitDataPage: FC = () => {
  const initDataRaw = useLaunchParams().initDataRaw;
  const initData = useInitData();

  const initDataRows = useMemo<DisplayDataRow[] | undefined>(() => {
    if (!initData || !initDataRaw) {
      return;
    }
    const {
      hash,
      queryId,
      chatType,
      chatInstance,
      authDate,
      startParam,
      canSendAfter,
      canSendAfterDate,
    } = initData;
    return [
      { title: 'raw', value: initDataRaw },
      { title: 'auth_date', value: authDate.toLocaleString() },
      { title: 'auth_date (raw)', value: authDate.getTime() / 1000 },
      { title: 'hash', value: hash },
      { title: 'can_send_after', value: canSendAfterDate?.toISOString() },
      { title: 'can_send_after (raw)', value: canSendAfter },
      { title: 'query_id', value: queryId },
      { title: 'start_param', value: startParam },
      { title: 'chat_type', value: chatType },
      { title: 'chat_instance', value: chatInstance },
    ];
  }, [initData, initDataRaw]);

  const userRows = useMemo<DisplayDataRow[] | undefined>(() => {
    return initData && initData.user ? getUserRows(initData.user) : undefined;
  }, [initData]);

  const receiverRows = useMemo<DisplayDataRow[] | undefined>(() => {
    return initData && initData.receiver ? getUserRows(initData.receiver) : undefined;
  }, [initData]);

  const chatRows = useMemo<DisplayDataRow[] | undefined>(() => {
    if (!initData?.chat) {
      return;
    }
    const { id, title, type, username, photoUrl } = initData.chat;

    return [
      { title: 'id', value: id.toString() },
      { title: 'title', value: title },
      { title: 'type', value: type },
      { title: 'username', value: username },
      { title: 'photo_url', value: photoUrl },
    ];
  }, [initData]);

  let contentNode: ReactNode;

  if (!initDataRows) {
    contentNode = <i>Application was launched with missing init data</i>;
  } else {
    contentNode = (
      <>
        <div className="init-data-page__section">
          <h2 className="init-data-page__section-title">Init data</h2>
          <DisplayData rows={initDataRows} />
        </div>

        <div className="init-data-page__section">
          <h2 className="init-data-page__section-title">User</h2>
          {userRows
            ? <DisplayData rows={userRows} />
            : <i>User information missing</i>}
        </div>

        <div className="init-data-page__section">
          <h2 className="init-data-page__section-title">Receiver</h2>
          {receiverRows
            ? <DisplayData rows={receiverRows} />
            : <i>Receiver information missing</i>}
        </div>

        <div className="init-data-page__section">
          <h2 className="init-data-page__section-title">Chat</h2>
          {chatRows
            ? <DisplayData rows={chatRows} />
            : <i>Chat information missing</i>}
        </div>
      </>
    );
  }

  return (
    <Page
      title="Init Data"
      disclaimer={(
        <>
          This page displays application
          {' '}
          <Link to="https://docs.telegram-mini-apps.com/platform/launch-parameters">
            init data
          </Link>
          .
        </>
      )}
    >
      {contentNode}
    </Page>
  );
};

// templates/solidjs-template/src/pages/InitDataPage/InitDataPage.tsx
import { retrieveLaunchParams, useInitData, type User } from '@tma.js/sdk-solid';
import { createMemo, Show } from 'solid-js';
import type { Component } from 'solid-js';

import { DisplayData, type DisplayDataRow } from '@/components/DisplayData/DisplayData.js';
import { Link } from '@/components/Link/Link.js';
import { Page } from '@/components/Page/Page.js';

import './InitDataPage.css';

function getUserRows(user: User): DisplayDataRow[] {
  return [
    { title: 'id', value: user.id.toString() },
    { title: 'last_name', value: user.lastName },
    { title: 'first_name', value: user.firstName },
    { title: 'is_bot', value: user.isBot },
    { title: 'is_premium', value: user.isPremium },
    { title: 'language_code', value: user.languageCode },
  ];
}

export const InitDataPage: Component = () => {
  const initData = useInitData();
  const initDataRaw = retrieveLaunchParams().initDataRaw;

  const initDataRows = createMemo<DisplayDataRow[] | undefined>(() => {
    const complete = initData();

    return complete && initDataRaw
      ? [
        { title: 'raw', value: initDataRaw },
        { title: 'auth_date', value: complete.authDate.toLocaleString() },
        { title: 'auth_date (raw)', value: complete.authDate.getTime() / 1000 },
        { title: 'hash', value: complete.hash },
        { title: 'can_send_after', value: complete.canSendAfterDate?.toISOString() },
        { title: 'can_send_after (raw)', value: complete.canSendAfter },
        { title: 'query_id', value: complete.queryId },
        { title: 'start_param', value: complete.startParam },
        { title: 'chat_type', value: complete.chatType },
        { title: 'chat_instance', value: complete.chatInstance },
      ]
      : undefined;
  });

  const userRows = createMemo<DisplayDataRow[] | undefined>(() => {
    const user = initData()?.user;
    return user ? getUserRows(user) : undefined;
  });

  const receiverRows = createMemo<DisplayDataRow[] | undefined>(() => {
    const receiver = initData()?.receiver;
    return receiver ? getUserRows(receiver) : undefined;
  });

  const chatRows = createMemo<DisplayDataRow[] | undefined>(() => {
    const chat = initData()?.chat;
    return chat
      ? [
        { title: 'id', value: chat.id.toString() },
        { title: 'title', value: chat.title },
        { title: 'type', value: chat.type },
        { title: 'username', value: chat.username },
        { title: 'photo_url', value: chat.photoUrl },
      ]
      : undefined;
  });

  return (
    <Page
      title="Init Data"
      disclaimer={(
        <>
          This page displays application
          {' '}
          <Link href="https://docs.telegram-mini-apps.com/platform/launch-parameters">
            init data
          </Link>
          .
        </>
      )}
    >
      <Show when={initDataRows()} fallback={<i>Application was launched with missing init data</i>}>
        {(rows) => (
          <>
            <div class="init-data-page__section">
              <h2 class="init-data-page__section-title">Init data</h2>
              <DisplayData rows={rows()}/>
            </div>

            <div class="init-data-page__section">
              <h2 class="init-data-page__section-title">User</h2>
              <Show when={userRows()} fallback={<i>User information missing</i>}>
                {(uRows) => <DisplayData rows={uRows()}/>}
              </Show>
            </div>

            <div class="init-data-page__section">
              <h2 class="init-data-page__section-title">Receiver</h2>
              <Show when={receiverRows()} fallback={<i>Receiver information missing</i>}>
                {(rRows) => <DisplayData rows={rRows()}/>}
              </Show>
            </div>

            <div class="init-data-page__section">
              <h2 class="init-data-page__section-title">Chat</h2>
              <Show when={chatRows()} fallback={<i>Chat information missing</i>}>
                {(cRows) => <DisplayData rows={cRows()}/>}
              </Show>
            </div>
          </>
        )}
      </Show>
    </Page>
  );
};
