// templates/reactjs-js-template/src/components/RGB/RGB.jsx
import { classNames } from '@tma.js/sdk-react';

import './RGB.css';

/**
 * @param {import('@tma.js/sdk-react').RGB} color
 * @param {string} [className]
 * @param rest
 * @return {JSX.Element}
 */
export function RGB({ color, className, ...rest }) {
  return (
    <span {...rest} className={classNames('rgb', className)}>
      <i className="rgb__icon" style={{ backgroundColor: color }} />
      {color}
    </span>
  );
}

// templates/solidjs-js-template/src/components/RGB/RGB.jsx
import { classNames } from '@tma.js/sdk-solid';
import { splitProps } from 'solid-js';

import './RGB.css';

/**
 * @typedef RGBProps
 * @extends {import('solid-js').JSX.IntrinsicElements['span']}
 * @property {import('@tma.js/sdk-solid').RGB} color
 */

/**
 * @param {RGBProps} props
 * @return {import('solid-js').JSXElement}
 */
export function RGB(props) {
  return (
    <span {...splitProps(props, ['class'])[0]} class={classNames('rgb', props.class)}>
      <i class="rgb__icon" style={{ 'background-color': props.color }}/>
        {props.color}
    </span>
  );
}
