// playgrounds/solid/src/components/Root.tsx
import { ErrorBoundary, type Component, Switch, Match } from 'solid-js';

import { App } from '@/components/App.js';
import { TonConnectUIProvider } from '@/tonconnect/TonConnectUIProvider.js';

const Inner: Component = () => (
  <TonConnectUIProvider
    manifestUrl={new URL('tonconnect-manifest.json', window.location.href).toString()}
  >
    <App/>
  </TonConnectUIProvider>
);

export const Root: Component = () => (
  <ErrorBoundary
    fallback={err => {
      throw err;
      console.error('ErrorBoundary handled error:', err);

      return (
        <div>
          <p>ErrorBoundary handled error:</p>
          <blockquote>
            <code>
              <Switch fallback={JSON.stringify(err)}>
                <Match when={typeof err === 'string' ? err : false}>
                  {v => v()}
                </Match>
                <Match when={err instanceof Error ? err.message : false}>
                  {v => v()}
                </Match>
              </Switch>
            </code>
          </blockquote>
        </div>
      );
    }}
  >
    <Inner/>
  </ErrorBoundary>
)

// playgrounds/react/src/components/Root.tsx
import { TonConnectUIProvider } from '@tonconnect/ui-react';

import { App } from '@/components/App.tsx';
import { ErrorBoundary } from '@/components/ErrorBoundary.tsx';

function ErrorBoundaryError({ error }: { error: unknown }) {
  return (
    <div>
      <p>An unhandled error occurred:</p>
      <blockquote>
        <code>
          {error instanceof Error
            ? error.message
            : typeof error === 'string'
              ? error
              : JSON.stringify(error)}
        </code>
      </blockquote>
    </div>
  );
}

export function Root() {
  return (
    <ErrorBoundary fallback={ErrorBoundaryError}>
      <TonConnectUIProvider
        manifestUrl={new URL('/tonconnect-manifest.json', window.location.href).toString()}
      >
        <App/>
      </TonConnectUIProvider>
    </ErrorBoundary>
  );
}
