// apps/react-sdk-example/src/Root.tsx
import { PropsWithChildren, useEffect, useMemo, useState } from 'react';
import { SDKProvider, useSDK, useMainButton, useBackButton, useInitData } from '@tma.js/sdk-react';

function MainButtonTest() {
  const mainButton = useMainButton();
  const backButton = useBackButton();

  const [count, setCount] = useState(0);

  useEffect(() => {
    const onMainButtonClick = () => setCount((count) => count + 1);
    const onBackButtonClick = () => setCount((count) => count - 1);

    mainButton.enable().show();
    mainButton.on('click', onMainButtonClick);
    backButton.on('click', onBackButtonClick);

    return () => {
      mainButton.off('click', onMainButtonClick);
      mainButton.hide();
      backButton.off('click', onBackButtonClick);
    };
  }, []);

  useEffect(() => {
    mainButton.setText(`Count is ${count}`);
  }, [mainButton, count]);

  useEffect(() => {
    if (count === 0) {
      backButton.hide();
      return;
    }
    backButton.show();
  }, [backButton, count]);

  return null;
}

/**
 * Displays current application init data.
 */
function InitData() {
  const initData = useInitData();

  const initDataJson = useMemo(() => {
    if (!initData) {
      return 'Init data is empty.';
    }
    const { authDate, chat, hash, canSendAfter, queryId, receiver, user, startParam } = initData;

    return JSON.stringify({
      authDate,
      chat,
      hash,
      canSendAfter,
      queryId,
      receiver,
      user,
      startParam,
    }, null, ' ');
  }, [initData]);

  return (
    <pre>
      <code>
        {initDataJson}
      </code>
    </pre>
  );
}

/**
 * This component is the layer controlling the application display. It displays
 * application in case, the SDK is initialized, displays an error if something
 * went wrong, and a loader if the SDK is warming up.
 */
function DisplayGate({ children }: PropsWithChildren) {
  const { didInit, components, error } = useSDK();
  const errorMessage = useMemo<null | string>(() => {
    if (!error) {
      return null;
    }

    return error instanceof Error ? error.message : 'Unknown error';
  }, [error]);

  // There were no calls of SDK's init function. It means, we did not
  // even try to do it.
  if (!didInit) {
    return <div>SDK init function is not yet called.</div>;
  }

  // Error occurred during SDK init.
  if (error !== null) {
    return (
      <>
        <p>
          SDK was unable to initialize. Probably, current application is being used
          not in Telegram Web Apps environment.
        </p>
        <blockquote>
          <p>{errorMessage}</p>
        </blockquote>
      </>
    );
  }

  // If components is null, it means, SDK is not ready at the
  // moment and currently initializing. Usually, it takes like
  // several milliseconds or something like that, but we should
  // have this check.
  if (components === null) {
    return <div>Loading..</div>;
  }

  // Safely render application.
  return <>{children}</>;
}

/**
 * Root component of the whole project.
 */
export function Root() {
  return (
    <SDKProvider initOptions={{ debug: true, cssVars: true }}>
      <DisplayGate>
        <InitData/>
        <MainButtonTest/>
      </DisplayGate>
    </SDKProvider>
  );
}

// apps/solid-sdk-example/src/Root.tsx
import {
  createMemo,
  Switch,
  Match,
  ParentProps,
  createSignal,
  createEffect,
  onMount, onCleanup,
} from 'solid-js';
import { SDKProvider, useSDK, useSDKContext } from '@tma.js/sdk-solid';

function MainButtonTest() {
  const { mainButton, backButton } = useSDK();

  const [count, setCount] = createSignal(0);

  onMount(() => {
    const bb = backButton();
    const mb = mainButton();

    const onMainButtonClick = () => setCount((count) => count + 1);
    const onBackButtonClick = () => setCount((count) => count - 1);

    mb.enable().show().on('click', onMainButtonClick);
    bb.on('click', onBackButtonClick);

    onCleanup(() => {
      mb.hide().off('click', onMainButtonClick);
      bb.off('click', onBackButtonClick);
    });
  });

  createEffect(() => {
    mainButton().setText(`Count is ${count()}`);
  });

  createEffect(() => {
    const bb = backButton();

    if (count() === 0) {
      bb.hide();
      return;
    }
    bb.show();
  });

  return null;
}

/**
 * Displays current application init data.
 */
function InitData() {
  const { initData } = useSDK();

  const initDataJson = createMemo(() => {
    const obj = initData();

    if (!obj) {
      return 'Init data is empty.';
    }
    const { authDate, chat, hash, canSendAfter, queryId, receiver, user, startParam } = obj;

    return JSON.stringify({
      authDate,
      chat,
      hash,
      canSendAfter,
      queryId,
      receiver,
      user,
      startParam,
    }, null, ' ');
  });

  return (
    <pre>
      <code>
        {initDataJson()}
      </code>
    </pre>
  );
}

/**
 * Component which is responsible for controlling SDK init process.
 */
function DisplayGate(props: ParentProps) {
  const { loading, error } = useSDKContext();
  const errorMessage = createMemo<null | string>(() => {
    const err = error();

    if (!err) {
      return null;
    }

    return err instanceof Error ? err.message : 'Unknown error';
  });

  return (
    <Switch fallback={props.children}>
      <Match when={errorMessage()}>
        <p>
          SDK was unable to initialize. Probably, current application is being used
          not in Telegram Web Apps environment.
        </p>
        <blockquote>
          <p>{errorMessage()}</p>
        </blockquote>
      </Match>
      <Match when={loading()}>
        <div>Loading..</div>
      </Match>
    </Switch>
  );
}

/**
 * Root component of the project.
 */
export function Root() {
  return (
    <SDKProvider initOptions={{ debug: true, cssVars: true, timeout: 1000 }}>
      <DisplayGate>
        <InitData/>
        <MainButtonTest/>
      </DisplayGate>
    </SDKProvider>
  );
}
