// playgrounds/svelte/src/components/Page/Page.svelte
<script lang="ts">
  import './Page.css';

  interface IProps {
    title: string,
    children?: Snippet,
    disclaimer?: Snippet
  }

  import type { Snippet } from 'svelte';

  const { title, disclaimer, children }: IProps = $props();
</script>

<main class="page">
  <h1>{title}</h1>
  {#if disclaimer}
    <div class="page__disclaimer">{@render disclaimer()}</div>
  {/if}
  {@render children?.()}
</main>

// apps/react/src/components/Page/Page.tsx
import type { FC, PropsWithChildren, ReactNode } from 'react';

import './Page.css';

export interface PageProps extends PropsWithChildren {
  title: string;
  disclaimer?: ReactNode;
}

export const Page: FC<PageProps> = ({ title, children, disclaimer }) => (
  <div className="page">
    <h1>{title}</h1>
    {disclaimer && <div className="page__disclaimer">{disclaimer}</div>}
    {children}
  </div>
);
