// apps/solid/src/components/DisplayData/DisplayData.tsx
import { isRGB, type RGB as RGBType } from '@tma.js/sdk-solid';
import { type Component, For, type JSXElement, Match, Switch } from 'solid-js';

import { RGB } from '@/components/RGB/RGB.js';

import './DisplayData.css';

export interface DisplayDataRow {
  title: string;
  value?: RGBType | string | boolean | JSXElement;
}

export interface DisplayDataProps {
  rows: DisplayDataRow[];
}

export const DisplayData: Component<DisplayDataProps> = (props) => {
  return (
    <div>
      <For each={props.rows}>
        {(row) => (
          <div class="display-data__line">
            <span class="display-data__line-title">{row.title}</span>
            <span class="display-data__line-value">
              <Switch fallback={row.value}>
                <Match when={typeof row.value === 'string' && isRGB(row.value) ? row.value : false}>
                  {(color) => <RGB color={color()}/>}
                </Match>
                <Match when={row.value === false}>❌</Match>
                <Match when={row.value === true}>✔️</Match>
                <Match when={row.value === undefined}><i>empty</i></Match>
              </Switch>
            </span>
          </div>
        )}
      </For>
    </div>
  );
};

// apps/react/src/components/DisplayData/DisplayData.tsx
import { isRGB, type RGB as RGBType } from '@tma.js/sdk';
import type { FC, ReactNode } from 'react';

import { RGB } from '@/components/RGB/RGB.tsx';

import './DisplayData.css';

export interface DisplayDataRow {
  title: string;
  value?: RGBType | string | boolean | ReactNode;
}

export interface DisplayDataProps {
  rows: DisplayDataRow[];
}

export const DisplayData: FC<DisplayDataProps> = ({ rows }) => (
  <div>
    {rows.map(({ title, value }, idx) => {
      let valueNode: ReactNode;

      if (value === undefined) {
        valueNode = <i>empty</i>;
      } else if (typeof value === 'string' && isRGB(value)) {
        valueNode = <RGB color={value} />;
      } else if (typeof value === 'boolean') {
        valueNode = value ? '✔️' : '❌';
      } else {
        valueNode = value;
      }

      return (
        <div className="display-data__line" key={idx}>
          <span className="display-data__line-title">{title}</span>
          <span className="display-data__line-value">{valueNode}</span>
        </div>
      );
    })}
  </div>
);
