// apps/solid/src/pages/TonConnectPage/TonConnectPage.tsx
import { Show, type Component } from 'solid-js';

import { DisplayData } from '@/components/DisplayData/DisplayData.js';
import { Link } from '@/components/Link/Link.js';
import { Page } from '@/components/Page/Page.js';
import { TonConnectButton } from '@/tonconnect/TonConnectButton.js';
import { useTonWallet } from '@/tonconnect/useTonWallet.js';

import './TonConnectPage.css';

export const TonConnectPage: Component = () => {
  const wallet = useTonWallet();

  return (
    <Page title="TON Connect">
      <Show
        when={wallet()}
        fallback={
          <p>
            To display the data related to the TON Connect, it is required to connect your wallet.
          </p>
        }
      >
        {(walletBasic) => {
          const walletExtended = () => {
            const w = walletBasic();
            return 'imageUrl' in w ? w : null;
          };
          const account = () => walletBasic().account;

          return (
            <>
              <Show when={walletExtended()}>
                {(w) => (
                  <div class="ton-connect-page__provider">
                    <img
                      class="ton-connect-page__provider-image"
                      alt="Provider logo"
                      src={w().imageUrl}
                      width={60}
                      height={60}
                    />
                    <div class="ton-connect-page__provider-meta">
                      <p class="ton-connect-page__provider-wallet-name">
                        {w().name}&nbsp;
                        <span class="ton-connect-page__provider-app-name">
                          ({w().appName})
                        </span>
                      </p>
                      <Link href={w().aboutUrl}>
                        About connected wallet
                      </Link>
                    </div>
                  </div>
                )}
              </Show>
              <DisplayData
                rows={[
                  { title: 'Address', value: account().address },
                  { title: 'Chain', value: account().chain },
                  { title: 'Public Key', value: account().publicKey },
                ]}
              />
            </>
          );
        }}
      </Show>
      <div class="ton-connect-page__button-container">
        <TonConnectButton/>
      </div>
    </Page>
  );
};

// playgrounds/svelte/src/pages/TonConnectPage/TonConnectPage.svelte
<script lang="ts">
  import Page from '@/components/Page/Page.svelte';
  import { useTonWallet, TonConnectButton } from '@/tonconnect';
  import DisplayData from '@/components/DisplayData/DisplayData.svelte';
  import Link from '@/components/Link/Link.svelte';
  import { derived, type Writable } from 'svelte/store';
  import type { ConnectedWallet } from '@tonconnect/ui';

  import './TonConnectPage.css';

  const wallet: Writable<ConnectedWallet> = useTonWallet();

  const walletExtended = derived(wallet, ($wallet) => {
    return $wallet && 'imageUrl' in $wallet ? $wallet : null;
  });

  const rows = derived(wallet, ($wallet) => {
    return $wallet
      ? [
          { title: 'Address', value: $wallet.account.address },
          { title: 'Chain', value: $wallet.account.chain },
          { title: 'Public Key', value: $wallet.account.publicKey },
        ]
      : [];
  });
</script>

<Page title="TON Connect">
  {#if !$wallet}
    <p>
      To display the data related to the TON Connect, it is required to connect
      your wallet.
    </p>
  {:else if $walletExtended}
    <div class="ton-connect-page__provider">
      <img
        class="ton-connect-page__provider-image"
        src={$walletExtended.imageUrl}
        alt="Provider logo"
        width="60"
        height="60"
      />
      <div class="ton-connect-page__provider-meta">
        <p class="ton-connect-page__provider-wallet-name">
          {$walletExtended.name}&nbsp;
          <span class="ton-connect-page__provider-app-name">
            {$walletExtended.appName}
          </span>
        </p>
        <Link
          path={$walletExtended.aboutUrl}
          title={'About connected wallet'}
        />
        <DisplayData rows={$rows} />
      </div>
    </div>
  {/if}
  <div class="ton-connect-page__button-container">
    <TonConnectButton />
  </div>
</Page>
