// playgrounds/react/src/pages/LaunchParamsPage.tsx
import { useLaunchParams } from '@telegram-apps/sdk-react';
import { List } from '@telegram-apps/telegram-ui';
import type { FC } from 'react';

import { DisplayData } from '@/components/DisplayData/DisplayData.tsx';
import { Page } from '@/components/Page.tsx';

export const LaunchParamsPage: FC = () => {
  const lp = useLaunchParams();

  return (
    <Page>
      <List>
        <DisplayData
          rows={[
            { title: 'tgWebAppPlatform', value: lp.platform },
            { title: 'tgWebAppShowSettings', value: lp.showSettings },
            { title: 'tgWebAppVersion', value: lp.version },
            { title: 'tgWebAppBotInline', value: lp.botInline },
            { title: 'tgWebAppStartParam', value: lp.startParam },
            { title: 'tgWebAppData', type: 'link', value: '/init-data' },
            { title: 'tgWebAppThemeParams', type: 'link', value: '/theme-params' },
          ]}
        />
      </List>
    </Page>
  );
};

// playgrounds/svelte/src/pages/LaunchParamsPage/LaunchParamsPage.svelte
<script lang="ts">
    import Page from '@/components/Page/Page.svelte';
    import DisplayData from '@/components/DisplayData/DisplayData.svelte';
    import { useLaunchParams } from '@telegram-apps/sdk-svelte';
    import Link from '@/components/Link/Link.svelte';
  
    const lp = useLaunchParams();
    
    const rows = [
    { title: 'tgWebAppPlatform', value: lp.platform },
    { title: 'tgWebAppShowSettings', value: lp.showSettings },
    { title: 'tgWebAppVersion', value: lp.version },
    { title: 'tgWebAppBotInline', value: lp.botInline },
    { title: 'tgWebAppStartParam', value: lp.startParam },
    { title: 'tgWebAppData', value: Link, meta: { path: '/svelte-template/init-data', title: 'View' }},
    { title: 'tgWebAppThemeParams', value: Link, meta: { path: '/svelte-template/theme-params', title: 'View' } },
    ];
  </script>
  
  <Page title="Theme Params">
    {#snippet disclaimer()}
      This page displays current theme params.
    {/snippet}
    <DisplayData {rows} />
  </Page>
