// apps/react/src/components/Page/Page.tsx
import type { FC, PropsWithChildren, ReactNode } from 'react';

import './Page.css';

export interface PageProps extends PropsWithChildren {
  title: string;
  disclaimer?: ReactNode;
}

export const Page: FC<PageProps> = ({ title, children, disclaimer }) => (
  <div className="page">
    <h1>{title}</h1>
    {disclaimer && <div className="page__disclaimer">{disclaimer}</div>}
    {children}
  </div>
);

// playgrounds/solid/src/components/Page/Page.tsx
import type { Component, JSX, ParentProps } from 'solid-js';

import './Page.css';

export interface PageProps extends ParentProps {
  title: string;
  disclaimer?: JSX.Element;
}

export const Page: Component<PageProps> = (props) => {
  return (
    <div class="page">
      <h1>{props.title}</h1>
      {props.disclaimer && <div class="page__disclaimer">{props.disclaimer}</div>}
      {props.children}
    </div>
  );
};
