// templates/reactjs-js-template/src/components/Page/Page.jsx
import './Page.css';

/**
 * @param {string} title
 * @param {import('react').ReactNode} [children]
 * @param {import('react').ReactNode} [disclaimer]
 * @return {JSX.Element}
 */
export function Page({ title, children, disclaimer }) {
  return (
    <div className="page">
      <h1>{title}</h1>
      {disclaimer && <div className="page__disclaimer">{disclaimer}</div>}
      {children}
    </div>
  );
}

// playgrounds/solid/src/components/Page/Page.tsx
import type { Component, JSX, ParentProps } from 'solid-js';

import './Page.css';

export interface PageProps extends ParentProps {
  title: string;
  disclaimer?: JSX.Element;
}

export const Page: Component<PageProps> = (props) => {
  return (
    <div class="page">
      <h1>{props.title}</h1>
      {props.disclaimer && <div class="page__disclaimer">{props.disclaimer}</div>}
      {props.children}
    </div>
  );
};
