// templates/solidjs-template/src/components/RGB/RGB.tsx
import { classNames, type RGB as RGBType } from '@tma.js/sdk-solid';
import { type Component, type JSX, splitProps } from 'solid-js';

import './RGB.css';

export type RGBProps = JSX.IntrinsicElements['span'] & {
  color: RGBType;
};

export const RGB: Component<RGBProps> = (props) => (
  <span {...splitProps(props, ['class'])[0]} class={classNames('rgb', props.class)}>
    <i class="rgb__icon" style={{ 'background-color': props.color }}/>
    {props.color}
  </span>
);

// templates/reactjs-template/src/components/RGB/RGB.tsx
import { classNames, type RGB as RGBType } from '@tma.js/sdk';
import type { FC } from 'react';

import './RGB.css';

export type RGBProps = JSX.IntrinsicElements['div'] & {
  color: RGBType;
};

export const RGB: FC<RGBProps> = ({ color, className, ...rest }) => (
  <span {...rest} className={classNames('rgb', className)}>
    <i className='rgb__icon' style={{ backgroundColor: color }}/>
    {color}
  </span>
);
