// templates/solidjs-js-template/src/pages/TonConnectPage/TonConnectPage.jsx
import { Show } from 'solid-js';

import { DisplayData } from '@/components/DisplayData/DisplayData.jsx';
import { Link } from '@/components/Link/Link.jsx';
import { Page } from '@/components/Page/Page.jsx';
import { TonConnectButton } from '@/tonconnect/TonConnectButton.jsx';
import { useTonWallet } from '@/tonconnect/useTonWallet.js';

import './TonConnectPage.css';

export function TonConnectPage() {
  const wallet = useTonWallet();

  return (
    <Page title="TON Connect">
      <Show
        when={wallet()}
        fallback={
          <p>
            To display the data related to the TON Connect, it is required to connect your wallet.
          </p>
        }
      >
        {(walletBasic) => {
          const walletExtended = () => {
            const w = walletBasic();
            return 'imageUrl' in w ? w : null;
          };
          const account = () => walletBasic().account;

          return (
            <>
              <Show when={walletExtended()}>
                {(w) => (
                  <div class="ton-connect-page__provider">
                    <img
                      class="ton-connect-page__provider-image"
                      alt="Provider logo"
                      src={w().imageUrl}
                      width={60}
                      height={60}
                    />
                    <div class="ton-connect-page__provider-meta">
                      <p class="ton-connect-page__provider-wallet-name">
                        {w().name}&nbsp;
                        <span class="ton-connect-page__provider-app-name">
                          ({w().appName})
                        </span>
                      </p>
                      <Link href={w().aboutUrl}>
                        About connected wallet
                      </Link>
                    </div>
                  </div>
                )}
              </Show>
              <DisplayData
                rows={[
                  { title: 'Address', value: account().address },
                  { title: 'Chain', value: account().chain },
                  { title: 'Public Key', value: account().publicKey },
                ]}
              />
            </>
          );
        }}
      </Show>
      <div class="ton-connect-page__button-container">
        <TonConnectButton/>
      </div>
    </Page>
  );
}

// templates/reactjs-js-template/src/pages/TONConnectPage/TONConnectPage.jsx
import { useUtils } from '@tma.js/sdk-react';
import { TonConnectButton, useTonWallet } from '@tonconnect/ui-react';

import { DisplayData } from '@/components/DisplayData/DisplayData.jsx';
import { Link } from '@/components/Link/Link.jsx';
import { Page } from '@/components/Page/Page.jsx';

import './TONConnectPage.css';

/**
 * @returns {JSX.Element}
 */
export function TONConnectPage() {
  const wallet = useTonWallet();
  const utils = useUtils();
  let content;

  if (wallet) {
    const {
      chain,
      publicKey,
      address,
    } = wallet.account;
    content = (
      <>
        {'imageUrl' in wallet && (
          <div className="ton-connect-page__provider">
            <img
              className="ton-connect-page__provider-image"
              alt="Provider logo"
              src={wallet.imageUrl}
              width={60}
              height={60}
            />
            <div className="ton-connect-page__provider-meta">
              <p className="ton-connect-page__provider-wallet-name">
                {wallet.name}
                &nbsp;
                <span className="ton-connect-page__provider-app-name">
                  (
                  {wallet.appName}
                  )
                </span>
              </p>
              <Link
                to={wallet.aboutUrl}
                onClick={(e) => {
                  e.preventDefault();
                  utils.openLink(wallet.aboutUrl);
                }}
              >
                About connected wallet
              </Link>
            </div>
          </div>
        )}
        <DisplayData
          rows={[
            { title: 'Address', value: address },
            { title: 'Chain', value: chain },
            { title: 'Public Key', value: publicKey },
          ]}
        />
      </>
    );
  } else {
    content = (
      <p>
        To display the data related to the TON Connect, it is required to connect your wallet.
      </p>
    );
  }

  return (
    <Page title="TON Connect">
      {content}
      <div className="ton-connect-page__button-container">
        <TonConnectButton />
      </div>
    </Page>
  );
}
