// packages/sdk-react/src/sdk/SDKProvider.tsx
import React, {
  memo,
  PropsWithChildren, useEffect,
  useMemo,
  useState,
} from 'react';
import {init, InitOptions} from '@twa.js/sdk';

import {sdkContext} from './context';
import {SDKComponents, SDKContext} from './types';

export type SDKProviderProps = PropsWithChildren<{ initOptions?: InitOptions }>;

/**
 * Component which provides access to SDK components.
 */
export const SDKProvider = memo<SDKProviderProps>(props => {
  const {children, initOptions} = props;
  const [didInit, setDidInit] = useState(false);
  const [error, setError] = useState<null | unknown>(null);
  const [components, setComponents] = useState<SDKComponents | null>(null);

  // Initialize SDK on DOM attach.
  useEffect(() => {
    // Update init status.
    setDidInit(true);

    // Init SDK.
    init(initOptions)
      .then(setComponents)
      .catch(setError);
  }, []);

  const context = useMemo<SDKContext>(() => ({
    components,
    didInit,
    error,
  }), [didInit, components, error]);

  return <sdkContext.Provider value={context}>{children}</sdkContext.Provider>;
});

SDKProvider.displayName = 'SDKProvider';

// packages/sdk-solid/src/SDKProvider.tsx
import { createMemo, createResource, ParentProps } from 'solid-js';
import { init } from '@twa.js/sdk';

import { SDKContext } from './context.js';
import type { SDKInitOptions } from './types.js';

export type SDKProviderProps = ParentProps<{ initOptions?: SDKInitOptions }>;

export function SDKProvider(props: SDKProviderProps) {
  const initOptions = createMemo(() => props.initOptions || {});
  const [data] = createResource(initOptions, init);

  const initResult = createMemo(() => {
    return data.state === 'ready' ? data() : null;
  });
  const loading = createMemo(() => data.loading);
  const error = createMemo(() => data.error === undefined ? null : data.error);

  return (
    <SDKContext.Provider value={{ initResult, loading, error }}>
      {props.children}
    </SDKContext.Provider>
  );
}
