// playgrounds/solid/src/tonconnect/TonConnectButton.tsx
import { onCleanup, onMount, type Component } from 'solid-js';

import { useTonConnectUI } from '@/tonconnect/TonConnectUIContext.js';

export const TonConnectButton: Component = () => {
  const [, { setUIOptions }] = useTonConnectUI();
  const buttonRootId = 'ton-connect-button';

  onMount(() => {
    setUIOptions({ buttonRootId });
  });

  onCleanup(() => {
    setUIOptions({ buttonRootId: null });
  });

  return <div id={buttonRootId} style={{ width: 'fit-content' }}/>;
};

// playgrounds/svelte/src/tonconnect/TonConnectButton.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { useTonConnectUI } from './useTonConnectUI';
  import { derived } from 'svelte/store';

  let { id = 'tonconnect-button' } = $props();

  const contextValue = useTonConnectUI();

  const setTonConnectUIOptions = derived(
    contextValue,
    ($contextValue) => $contextValue.setTonConnectUIOptions
  );

  onMount(() => {
    $setTonConnectUIOptions({ buttonRootId: id });
  });

  onDestroy(() => {
    $setTonConnectUIOptions({ buttonRootId: null });
  });
</script>

<div {id} style="width: 'fit-content'"></div>
